name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint
        run: |
          flake8 addons
          pylint addons --rcfile=.pylintrc

      - name: Start Postgres
        run: docker run -d --name pg -e POSTGRES_DB=odoo -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -p 5432:5432 postgres:16

      - name: Build Odoo image (dev)
        run: docker build -t odoo-dev -f docker/Dockerfile .

      - name: Init DB
        run: |
          docker run --rm --link pg:db -e ODOO_DB_PASSWORD=odoo -e ODOO_ADMIN_PASSWORD=admin \
            odoo-dev odoo -c /etc/odoo/odoo.conf -d test_ci --stop-after-init

      - name: Run Odoo tests
        run: |
          docker run --rm --link pg:db -e ODOO_DB_PASSWORD=odoo -e ODOO_ADMIN_PASSWORD=admin \
            odoo-dev odoo -c /etc/odoo/odoo.conf -d test_ci \
              -i base,web --test-enable --stop-after-init           # ✅ أضف وحداتك
