name: Deploy Two Stagings

on:
  push:
    branches: [ staging ]     # ادفع إلى فرع staging للنشر
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage:
          - name: stage-a
            env: staging-a
            remote_dir: /home/deploy/odoo/stage-a
            compose_src: compose/stage-a.yml
            project: stagea
          - name: stage-b
            env: staging-b
            remote_dir: /home/deploy/odoo/stage-b
            compose_src: compose/stage-b.yml
            project: stageb

    environment: ${{ matrix.stage.env }}

    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload compose file
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            ${{ matrix.stage.compose_src }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ matrix.stage.remote_dir }}/compose.yml

      - name: Remote deploy
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          cd ${{ matrix.stage.remote_dir }}
          export POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'
          export ODOO_ADMIN_PASSWORD='${{ secrets.ODOO_ADMIN_PASSWORD }}'
          export GIT_REF='${{ github.sha }}'
          docker login ghcr.io -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_TOKEN }}
          COMPOSE_PROJECT_NAME=${{ matrix.stage.project }} docker compose --env-file <(env | egrep 'POSTGRES_PASSWORD|ODOO_ADMIN_PASSWORD|GIT_REF') -f compose.yml pull
          COMPOSE_PROJECT_NAME=${{ matrix.stage.project }} docker compose --env-file <(env | egrep 'POSTGRES_PASSWORD|ODOO_ADMIN_PASSWORD|GIT_REF') -f compose.yml up -d --remove-orphans
          docker system prune -f
          EOF
